package com.cristian.detectexam;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;

public class MainScreen extends javax.swing.JFrame {

    private DetectExam detectExam;
    private static MainScreen instance;

    public MainScreen() {
        initComponents();
        scaleBackgroundImage();
    }

    public static MainScreen getInstance() {
        if (instance == null) {
            instance = new MainScreen();
            // Configuración adicional si es necesario
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        visorImageExam = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        uploadButton = new javax.swing.JButton();
        infoIdStudentTittle = new javax.swing.JLabel();
        infoIdExamTittle = new javax.swing.JLabel();
        infoCorrectAnswerTittle = new javax.swing.JLabel();
        infoWrongAnswerTittle = new javax.swing.JLabel();
        infoNullAnswerTittle = new javax.swing.JLabel();
        infoScoreTittle = new javax.swing.JLabel();
        infoIdStudent = new javax.swing.JLabel();
        infoIdExam = new javax.swing.JLabel();
        infoCorrectAnswer = new javax.swing.JLabel();
        infoWrongAnswer = new javax.swing.JLabel();
        infoNullAnswer = new javax.swing.JLabel();
        infoScore = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(960, 867));
        setMinimumSize(new java.awt.Dimension(960, 867));
        setPreferredSize(new java.awt.Dimension(960, 867));
        setSize(new java.awt.Dimension(960, 867));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setMaximumSize(new java.awt.Dimension(960, 867));
        backgroundPanel.setMinimumSize(new java.awt.Dimension(960, 867));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(960, 867));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        visorImageExam.setBackground(new java.awt.Color(255, 255, 255));
        visorImageExam.setOpaque(true);
        backgroundPanel.add(visorImageExam, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 450, 670));

        startButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        startButton.setForeground(new java.awt.Color(0, 0, 0));
        startButton.setText("COMENZAR");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        backgroundPanel.add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 740, 140, 50));

        uploadButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        uploadButton.setForeground(new java.awt.Color(0, 0, 0));
        uploadButton.setText("UPLOAD");
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });
        backgroundPanel.add(uploadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 740, 100, 30));

        infoIdStudentTittle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        infoIdStudentTittle.setForeground(new java.awt.Color(255, 255, 255));
        infoIdStudentTittle.setText("ID ESTUDIANTE");
        backgroundPanel.add(infoIdStudentTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 200, -1));

        infoIdExamTittle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        infoIdExamTittle.setForeground(new java.awt.Color(255, 255, 255));
        infoIdExamTittle.setText("ID EXAMEN");
        backgroundPanel.add(infoIdExamTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 200, -1));

        infoCorrectAnswerTittle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        infoCorrectAnswerTittle.setForeground(new java.awt.Color(255, 255, 255));
        infoCorrectAnswerTittle.setText("CORRECTAS");
        backgroundPanel.add(infoCorrectAnswerTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 200, -1));

        infoWrongAnswerTittle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        infoWrongAnswerTittle.setForeground(new java.awt.Color(255, 255, 255));
        infoWrongAnswerTittle.setText("INCORRECTAS");
        backgroundPanel.add(infoWrongAnswerTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 200, -1));

        infoNullAnswerTittle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        infoNullAnswerTittle.setForeground(new java.awt.Color(255, 255, 255));
        infoNullAnswerTittle.setText("NULAS");
        backgroundPanel.add(infoNullAnswerTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 200, -1));

        infoScoreTittle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        infoScoreTittle.setForeground(new java.awt.Color(255, 255, 255));
        infoScoreTittle.setText("PUNTUACIÓN");
        backgroundPanel.add(infoScoreTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 200, -1));

        infoIdStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        infoIdStudent.setForeground(new java.awt.Color(255, 255, 255));
        infoIdStudent.setText("ID ESTUDIANTE");
        backgroundPanel.add(infoIdStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 200, -1));

        infoIdExam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        infoIdExam.setForeground(new java.awt.Color(255, 255, 255));
        infoIdExam.setText("ID EXAMEN");
        backgroundPanel.add(infoIdExam, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 200, -1));

        infoCorrectAnswer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        infoCorrectAnswer.setForeground(new java.awt.Color(255, 255, 255));
        infoCorrectAnswer.setText("CORRECTAS");
        backgroundPanel.add(infoCorrectAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 200, -1));

        infoWrongAnswer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        infoWrongAnswer.setForeground(new java.awt.Color(255, 255, 255));
        infoWrongAnswer.setText("INCORRECTAS");
        backgroundPanel.add(infoWrongAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 200, -1));

        infoNullAnswer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        infoNullAnswer.setForeground(new java.awt.Color(255, 255, 255));
        infoNullAnswer.setText("NULAS");
        backgroundPanel.add(infoNullAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, 200, -1));

        infoScore.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        infoScore.setForeground(new java.awt.Color(255, 255, 255));
        infoScore.setText("PUNTUACIÓN");
        backgroundPanel.add(infoScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 200, -1));

        backgroundLabel.setBackground(new java.awt.Color(0, 27, 39));
        backgroundLabel.setMaximumSize(new java.awt.Dimension(960, 867));
        backgroundLabel.setMinimumSize(new java.awt.Dimension(960, 867));
        backgroundLabel.setName(""); // NOI18N
        backgroundLabel.setOpaque(true);
        backgroundLabel.setPreferredSize(new java.awt.Dimension(960, 867));
        backgroundPanel.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 867));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
        openFileChooser(0, new File("I:\\FPDAM\\PRACTICAS_EMPRESA\\recursosOpencv\\"));
    }//GEN-LAST:event_uploadButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
         if (DetectExam.getExamFile() != null) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        DetectExam.main(null);
                        setInfoExam();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            }).start();
        } else {
            System.out.println("Por favor, sube ambas imágenes antes de comenzar.");
        }
    }//GEN-LAST:event_startButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    private void openFileChooser(int flag, File initialDirectory) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("JPG Images", "jpg", "jpeg"));
        // Establecer la carpeta inicial
        fileChooser.setCurrentDirectory(initialDirectory);

        int returnValue = fileChooser.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            displayImage(selectedFile, flag);
        }
    }

    private void displayImage(File file, int flag) {
        try {
            ImageIcon originalIcon = new ImageIcon(file.getAbsolutePath());
            Image originalImage = originalIcon.getImage();
            System.out.println("urlImagen= " + file.getAbsolutePath());

            DetectExam.setExamFile(file.getAbsolutePath());
            int labelWidth = visorImageExam.getWidth();
            int labelHeight = visorImageExam.getHeight();

            Image scaledImage = originalImage.getScaledInstance(labelWidth, labelHeight, Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new ImageIcon(scaledImage);
            visorImageExam.setIcon(scaledIcon);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void setInfoExam() {
        SwingUtilities.invokeLater(() -> {
            infoIdStudent.setText(DetectExam.getIdStudent());
            infoIdExam.setText(DetectExam.getIdExam());
            infoCorrectAnswer.setText(String.valueOf(DetectExam.getCorrectAnswerCounter()));
            infoWrongAnswer.setText(String.valueOf(DetectExam.getWrongAnswerCounter()));
            infoNullAnswer.setText(String.valueOf(DetectExam.getNullAnswerCounter()));
            infoScore.setText(String.valueOf(DetectExam.getScore()));
            revalidate();
            repaint();
        });
    }

    private void scaleBackgroundImage() {
        java.net.URL imageUrl = getClass().getResource("/Fondo.png");
        if (imageUrl != null) {
            javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(imageUrl);
            Image originalImage = originalIcon.getImage();
            Image scaledImage = originalImage.getScaledInstance(backgroundLabel.getWidth(), backgroundLabel.getHeight(), java.awt.Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new javax.swing.ImageIcon(scaledImage);
            backgroundLabel.setIcon(scaledIcon);
        } else {
            System.err.println("Error: No se encontró la imagen en la ruta especificada.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel infoCorrectAnswer;
    private javax.swing.JLabel infoCorrectAnswerTittle;
    private javax.swing.JLabel infoIdExam;
    private javax.swing.JLabel infoIdExamTittle;
    private javax.swing.JLabel infoIdStudent;
    private javax.swing.JLabel infoIdStudentTittle;
    private javax.swing.JLabel infoNullAnswer;
    private javax.swing.JLabel infoNullAnswerTittle;
    private javax.swing.JLabel infoScore;
    private javax.swing.JLabel infoScoreTittle;
    private javax.swing.JLabel infoWrongAnswer;
    private javax.swing.JLabel infoWrongAnswerTittle;
    private javax.swing.JButton startButton;
    private javax.swing.JButton uploadButton;
    private javax.swing.JLabel visorImageExam;
    // End of variables declaration//GEN-END:variables
}
